### ISSUE TITLE
Investigate question generation from wiki-like texts

### ISSUE THREAD

**Issue by vshan** [IEEE-NITK/DeepNLP#15]
The Dual-LSTM Encoder model is pretty good as a retrieval-based model as compared to our Sequence-to-Sequence generation-based model. 

We want to create a training set for our retrieval-based model. We can extract questions from a sentence, for instance: 

Sentence: "The crownlands is one of the nine constituent regions of the Seven Kingdoms of Westeros."
Questions can be...

"What is the crownlands?"
"What is one of the nine constituent regions of the Seven Kingdoms of Westeros.?"

If we can make this possible, we can create a good training set for a retrieval-based Dual-LSTM Encoder model. 

More details for the Dual-LSTM encoder can be found [here](wildml.com/2016/07/deep-learning-for-chatbots-2-retrieval-based-model-tensorflow/).

**Comment by kaushiksk** [comment]
Any resources so i can help ?

**Comment by vshan** [comment]
http://www.iro.umontreal.ca/~felipe/TALN2010/Xml/Papers/taln/taln2010_submission_172.pdf

http://www.cs.cmu.edu/~ark/mheilman/questions/papers/heilman-question-generation-dissertation.pdf

Check these out.

**Comment by vshan** [comment]
#21 
#20 
I have added the question generation from wiki-sites.
