### ISSUE TITLE
Add Wikipedia/Wikia web crawler for facts-seeking questions

### ISSUE THREAD

**Issue by vshan** [IEEE-NITK/DeepNLP#4]
- This relates to #8. After a input is classified as facts-seeking, then we need to make an API call or write a crawler to find the response
- Find key words from query to answer

**Comment by arvindsaik** [comment]
Me and Aditya will be working on this issue.

**Comment by raoshashank** [comment]
this could be helpful:
http://textminingonline.com/getting-started-with-keyword-extraction

**Comment by sagar-bharadwaj-ks** [comment]
Me, @arvindsaik , and @aditya5558 will be working on this issue

**Comment by vshan** [comment]
Done along with question generation. Look into #20 #21
