### ISSUE TITLE
Create web interface / application for model API / whole project

### ISSUE THREAD

**Issue by vshan** [IEEE-NITK/DeepNLP#5]
Flask / Django

**Comment by grakshith** [comment]
https://github.com/tobegit3hub/deep_recommend_system/tree/master/http_service

**Comment by kaushiksk** [comment]
https://market.mashape.com/japerk/text-processing

http://text-processing.com/demo/

**Comment by kaushiksk** [comment]
@hehaichi @vshan We can use this as reference 

https://github.com/shekhargulati/52-technologies-in-2016/tree/master/11-textblob

**Comment by sbshah97** [comment]
@vshan Check this [link](https://github.com/IEEE-NITK/DeepNLP/tree/master/ui)
