### ISSUE TITLE
Add subtitle data to corpus, write web crawler

### ISSUE THREAD

**Issue by vshan** [IEEE-NITK/DeepNLP#6]
- Write web crawler to download game of thrones subtitle data
- Clean the data, make conversation pairs
- Combine with (cleaned) Book data to make one uniform corpus

**Comment by sbshah97** [comment]
Can you provide a more detailed description as to what to do here?
Also can I be assigned this Issue if possible!

**Comment by vshan** [comment]
@salman-bhai yeah I have edited the description and have assigned you. This issue is also related to #7 , please look into it. 

Also I found a [file](https://drive.google.com/open?id=0Bxlc-dr8ZjBjV0dmSm1pWmM4LWc) containing mostly all the subtitle data from all seasons. Needs preprocessing and cleaning.

**Comment by vshan** [comment]
@salman-bhai , since we already got the subtitle data and I did some cleaning, so I'll take over this issue now. I've assigned you another one.

**Comment by vshan** [comment]
#19 
Subtitle file is there, we can clean up that
