### ISSUE TITLE
Classify user response as fact-seeking or smalltalk

### ISSUE THREAD

**Issue by vshan** [IEEE-NITK/DeepNLP#8]
- Look into NLTK tools for ways to determine if user's input is either
  1. Fact-seeking: if it's fact-seeking then we can use Wikipedia or Wikia to answer user's query
  2. Smalltalk: user doesn't need a factual response, but a human-like conversation; in which case we pass the query to our chatbot model for response

- If NLTK is not sufficient, look into making a text classifier for the task

**Comment by aditya5558** [comment]
Me and Arvind will work on #4

**Comment by vshan** [comment]
check out https://cloud.google.com/natural-language/

**Comment by raoshashank** [comment]
http://www.aclweb.org/anthology/D08-1097

**Comment by vshan** [comment]
#20 
#21 
We have a rudimentary classifier working. Let's focus on other issues for now.
